INSERT INTO `reinsurers` (`id`, `raison_social`, `r_commerce`, `d_social`, `pays_id`, `active`, `user_id`, `created_at`,
                          `updated_at`, `deleted_at`)
VALUES (1, "AFRICAN RISK CAPACITY LIMITED AFRIQUE DU SUD", "", "", 1, 0, 0, NULL, NULL, NULL),
       (2, "AFRICA-RE COTE D'IVOIRE", NULL, NULL, 45, 0, 0, NULL, NULL, NULL),
       (3, "AMERICAN INTERNATIONAL GROUP France", "", "", 62, 0, 0, NULL, NULL, NULL),
       (4, "ARC RE", "", "", 112, 0, 0, NULL, NULL, NULL),
       (5, "AVENI-RE COTE D'IVOIRE", "", "", 45, 0, 0, NULL, NULL, NULL),
       (6, "AVENI-RE SENEGAL", "", "", 162, 0, 0, NULL, NULL, NULL),
       (7, "CCR RE FRANCE", "", "", 62, 0, 0, NULL, NULL, NULL),
       (8, "CHEDIDRE LIBAN", "", "", 98, 0, 0, NULL, NULL, NULL),
       (9, "CICA-RE CAMEROUN", "", "", 34, 0, 0, NULL, NULL, NULL),
       (10, "CICA-RE COTE D'IVOIRE", "", "", 45, 0, 0, NULL, NULL, NULL),
       (11, "CICA-RE TOGO", "", "", 182, 0, 0, NULL, NULL, NULL),
       (12, "CONTINENTAL RE COTE D'IVOIRE", "", "", 45, 0, 0, NULL, NULL, NULL),
       (13, "FBS RE", "", "", 126, 0, 0, NULL, NULL, NULL),
       (14, "GHANA-RE CAMEROUN", "", "", 34, 0, 0, NULL, NULL, NULL),
       (15, "GHANA-RE GHANA", "", "", 66, 0, 0, NULL, NULL, NULL),
       (16, "GLOBAL RE", "", "", 38, 0, 0, NULL, NULL, NULL),
       (17, "GLOBUS-RE BURKINA FASO", "", "", 31, 0, 0, NULL, NULL, NULL),
       (18, "GRAND REINSURANCE BOTSWANA", "", "", 27, 0, 0, NULL, NULL, NULL),
       (19, "HANNOVER RE ALLEMAGNE", "", "", 5, 0, 0, NULL, NULL, NULL),
       (20, "HANNOVER RE COTE D'IVOIRE", "", "", 45, 0, 0, NULL, NULL, NULL),
       (21, "HELVETIA ASSURANCES SA France", "", "", 62, 0, 0, NULL, NULL, NULL),
       (22, "HELVETIA ASSURANCES SA SENEGAL", "", "", 162, 0, 0, NULL, NULL, NULL),
       (23, "KEK RE", "", "", 66, 0, 0, NULL, NULL, NULL),
       (24, "KENYA-RE", "", "", 91, 0, 0, NULL, NULL, NULL),
       (25, "KENYA-RE COTE D'IVOIRE", "", "", 45, 0, 0, NULL, NULL, NULL),
       (26, "KLAPTON MANAGEMENT AFRICA", "", "", 45, 0, 0, NULL, NULL, NULL),
       (27, "KLAPTON REINSURANCE COTE D'IVOIRE", "", "", 45, 0, 0, NULL, NULL, NULL),
       (28, "KLAPTON REINSURANCE ZAMBIE", "", "", 196, 0, 0, NULL, NULL, NULL),
       (29, "MARE", "", "", 185, 0, 0, NULL, NULL, NULL),
       (30, "MUNICH RE AFRIQUE DU SUD", "", "", 1, 0, 0, NULL, NULL, NULL),
       (31, "NOUVELLE COMPAGNIE AFRICAINE DE REASSURANCE CI", "", "", 45, 0, 0, NULL, NULL, NULL),
       (32, "ODISSEYRE France", "", "", 62, 0, 0, NULL, NULL, NULL),
       (33, "POOL PVT AMGS", "", "", 45, 0, 0, NULL, NULL, NULL),
       (34, "SAUDI RE ARABIE SAOUDITE", "", "", 9, 0, 0, NULL, NULL, NULL),
       (35, "SCG-RE GABON", "", "", 63, 0, 0, NULL, NULL, NULL),
       (36, "SCOR SE FRANCE", "", "", 62, 0, 0, NULL, NULL, NULL),
       (37, "SCR COTE D'IVOIRE", "", "", 45, 0, 0, NULL, NULL, NULL),
       (38, "SCR MAROC", "", "", 111, 0, 0, NULL, NULL, NULL),
       (39, "SEN-RE SENEGAL", "", "", 162, 0, 0, NULL, NULL, NULL),
       (40, "SWISS RE AFRICA", "", "", 45, 0, 0, NULL, NULL, NULL),
       (41, "TUNIS-RE", "", "", 185, 0, 0, NULL, NULL, NULL),
       (42, "UMBRELLA REINSURANCE COMPANY LIBYE", "", "", 100, 0, 0, NULL, NULL, NULL),
       (43, "WAICA RE TUNISIE", "", "", 185, 0, 0, NULL, NULL, NULL),
       (44, "WAICA-RE COTE D'IVOIRE", NULL, NULL, 45, 0, 0, NULL, "2022-11-02 09:00:55", NULL),
       (45, "WAICA-RE GHANA", "", "", 66, 0, 0, NULL, NULL, NULL),
       (46, "WAICA-RE SIERRA LEONE", "", "", 165, 0, 0, NULL, NULL, NULL),
       (47, "W-SAFE REINSURANCE LTD GHANA", NULL, NULL, 66, 0, 0, NULL, "2022-10-31 12:33:03", NULL),
       (48, "ZEP-RE COTE D'IVOIRE", "", "", 45, 0, 0, NULL, NULL, NULL),
       (49, "ZEP-RE REPUBLIQUE DEMOCRATIQUE DU CONGO", "", "", 146, 0, 0, NULL, NULL, NULL),
       (62, "AMGS", NULL, NULL, 45, 1, 1, NULL, NULL, NULL);