INSERT INTO `transferors` (`id`, `pays_id`, `user_id`, `raison_social`, `r_commerce`, `d_social`, `nom`, `prenom`, `created_at`, `updated_at`, `deleted_at`)
VALUES
                                                                                                                                                                 (1, 146,1, 'ACTIVA ASSURANCES  RDC', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (2, 34,1, 'ACTIVA ASSURANCES CAMEROUN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (3, 45,1, 'ACTIVA ASSURANCES COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(4, 34,1, 'ACTIVA ASSURANCES VIE CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(5, 45,1, 'ACTIVA ASSURANCES VIE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (6, 70,1, 'ACTIVA ASSURANCES VIE GUINEE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (7, 45,1, 'AFRICAN RISK CAPACITY LIMITED AFRIQUE DU SUD', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (8, 45,1, 'AFRICA-RE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(9, 45,1, 'AGF ASSURANCES', '', '', '', '', NULL, NULL, NULL),
(10, 45,1, 'ALLIANZ COTE D\'IVOIRE ASSURANCES', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (11, 45,1, 'ALLIANZ COTE D\'IVOIRE ASSURANCES VIE', '', '', '', '', NULL, NULL, NULL),
(12, 111,1, 'ALLIANZ MALI', '', '', '', '', NULL, NULL, NULL),
(13, 45,1, 'ALPHA ASSURANCES', '', '', '', '', NULL, NULL, NULL),
(14, 62,1, 'AMERICAN INTERNATIONAL GROUP FRANCE', '', '', '', '', NULL, NULL, NULL),
(15, 45,1, 'AMSA ASSURANCES COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (16, 112,1, 'ARC RE MAURICE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (17, 34,1, 'AREA ASSURANCES CAMEROUN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (18, 45,1, 'ASSURANCES COMAR COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(19, 34,1, 'ASSURANCES GENERALES DU CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(20, 45,1, 'ATLANTA ASSURANCES COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (21, 21,1, 'ATLANTIQUE ASSURANCE BENIN VIE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (22, 21,1, 'ATLANTIQUE ASSURANCES BENIN IARDT', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (23, 45,1, 'ATLANTIQUE ASSURANCES COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(24, 45,1, 'ATLANTIQUE ASSURANCES VIE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (25, 182,1, 'ATLANTIQUE ASSURANCES VIE TOGO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (26, 45,1, 'ATLAS ASSURANCES COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(27, 45,1, 'AVENI-RE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (28, 162,1, 'AVENI-RE SENEGAL', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (29, 63,1, 'AXA ASSURANCES GABON', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (30, 45,1, 'AXA COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(31, 34,1, 'BENEFICIAL GENERAL CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(32, 34,1, 'CAMINSUR S.A CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(33, 62,1, 'CCR RE FRANCE', '', '', '', '', NULL, NULL, NULL),
(34, 34,1, 'CHANAS ASSURANCES CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(35, 98,1, 'CHEDIDRE LIBAN', '', '', '', '', NULL, NULL, NULL),
(36, 34,1, 'CICA-RE CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(37, 45,1, 'CICA-RE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (38, 182,1, 'CICA-RE TOGO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (39, 21,1, 'CIF ASSURANCE VIE BENIN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (40, 31,1, 'CIF ASSURANCES VIE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (41, 109,1, 'CNAR MALI', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (42, 34,1, 'COMPAGNIE PROFESSIONNELLE D’ASSURANCES (CPA) CAMEROUN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (43, 45,1, 'CONTINENTAL RE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(44, 31,1, 'CORIS ASSURANCE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
(45, 31,1, 'CORIS VIE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
(46, 126,1, 'FBS RE NIGERIA', '', '', '', '', NULL, NULL, NULL),
(47, 31,1, 'GA IARD BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
(48, 31,1, 'GA VIE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
(49, 45,1, 'GENERATION NOUVELLE D\'ASSURANCES COTE D\'IVOIRE (GNA-CI)', '', '', '', '', NULL, NULL, NULL),
(50, 34,1, 'GHANA-RE CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(51, 66,1, 'GHANA-RE GHANA', '', '', '', '', NULL, NULL, NULL),
(52, 38,1, 'GLOBAL RE', '', '', '', '', NULL, NULL, NULL),
(53, 31,1, 'GLOBUS-RE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
(54, 34,1, 'GMC ASSURANCES CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(55, 27,1, 'GRAND REINSURANCE BOTSWANA', '', '', '', '', NULL, NULL, NULL),
(56, 5,1, 'HANNOVER RE ALLEMAGNE', '', '', '', '', NULL, NULL, NULL),
(57, 45,1, 'HANNOVER RE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (58, 62,1, 'HELVETIA ASSURANCES SA FRANCE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (59, 162,1, 'HELVETIA ASSURANCES SA SENEGAL', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (60, 70,1, 'INTERNATIONAL INSURANCE COMPANY SA GUINEE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (61, 31,1, 'JACKSON ASSURANCE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (62, 66,1, 'KEK RE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (63, 91,1, 'KENYA-RE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (64, 45,1, 'KENYA-RE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(65, 45,1, 'KLAPTON MANAGEMENT AFRICA', '', '', '', '', NULL, NULL, NULL),
(66, 45,1, 'KLAPTON REINSURANCE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (67, 196,1, 'KLAPTON REINSURANCE ZAMBIE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (68, 21,1, 'LA GENERALE DES ASSURANCES BENIN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (69, 45,1, 'LA LOYALE ASSURANCES IARD COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(70, 45,1, 'LA LOYALE VIE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (71, 109,1, 'LAFIA MALI', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (72, 45,1, 'L\'AFRICAINE DES ASSURANCES COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (73, 21,1, 'L\'AFRICAINE VIE BENIN', '', '', '', '', NULL, NULL, NULL),
(74, 70,1, 'LANALA ASSURANCES GUINEE', '', '', '', '', NULL, NULL, NULL),
(75, 45,1, 'LEADWAY VIE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (76, 185,1, 'MARE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (77, 146,1, 'MAYFAIR INSURANCE RDC', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (78, 1,1, 'MUNICH RE AFRIQUE DU SUD', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (79, 70,1, 'MUTRAGUI SA GUINEE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (80, 45,1, 'MUTUELLE D\'ASSURANCES DES TAXIS COMPTEURS D\'ABIDJAN (MATCA) COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(81, 109,1, 'NALLIAS-SA MALI', '', '', '', '', NULL, NULL, NULL),
(82, 45,1, 'NOUVELLE COMPAGNIE AFRICAINE DE REASSURANCE CI', '', '', '', '', NULL, NULL, NULL),
(83, 21,1, 'NSIA ASSURANCES BENIN', '', '', '', '', NULL, NULL, NULL),
(84, 34,1, 'NSIA Assurances CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(85, 146,1, 'NSIA ASSURANCES CONGO', '', '', '', '', NULL, NULL, NULL),
(86, 45,1, 'NSIA ASSURANCES COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (87, 63,1, 'NSIA ASSURANCES GABON', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (88, 66,1, 'NSIA ASSURANCES GHANA', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (89, 70,1, 'NSIA ASSURANCES GUINEE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (90, 77,1, 'NSIA ASSURANCES GUINEE BISSAU', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (91, 109,1, 'NSIA ASSURANCES MALI', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (92, 126,1, 'NSIA ASSURANCES NIGERIA', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (93, 162,1, 'NSIA ASSURANCES SENEGAL', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (94, 182,1, 'NSIA ASSURANCES TOGO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (95, 21,1, 'NSIA ASSURANCES VIE BENIN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (96, 34,1, 'NSIA Assurances Vie CAMEROUN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (97, 146,1, 'NSIA ASSURANCES VIE CONGO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (98, 45,1, 'NSIA ASSURANCES VIE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(99, 63,1, 'NSIA ASSURANCES VIE GABON', '', '', '', '', NULL, NULL, NULL),
(100, 70,1, 'NSIA ASSURANCES VIE GUINEE', '', '', '', '', NULL, NULL, NULL),
(101, 109,1, 'NSIA ASSURANCES VIE MALI', '', '', '', '', NULL, NULL, NULL),
(102, 162,1, 'NSIA ASSURANCES VIE SENEGAL', '', '', '', '', NULL, NULL, NULL),
(103, 22,1, 'NSIA Assurances Vie TOGO', '', '', '', '', NULL, NULL, NULL),
(104, 45,1, 'OGAR GABON', '', '', '', '', NULL, NULL, NULL),
(105, 31,1, 'OLEA BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
(106, 62,1, 'ODISSEYRE FRANCE', '', '', '', '', NULL, NULL, NULL),
(107, 45,1, 'POOL PVT AMGS', '', '', '', '', NULL, NULL, NULL),
(108, 34,1, 'PRO ASSUR CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(109, 112,1, 'PRUDENTIAL BELIFE INSURANCE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (110, 45,1, 'RAY ASSURANCES MAURICE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (111, 146,1, 'RAWSUR LIFE RDC', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (112, 146,1, 'RAWSUR SA RDC', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (113, 31,1, 'RAYNAL IARD BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (114, 34,1, 'SAAR ASSURANCES CAMEROUN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (115, 70,1, 'SAAR ASSURANCES SA GUINEE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (116, 21,1, 'SAAR BENIN ASSURANCES', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (117, 109,1, 'SABU NYUMAN MALI', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (118, 21,1, 'SANLAM ASSURANCE BENIN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (119, 162,1, 'SALAMA SENEGAL', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (120, 31,1, 'SANLAM ASSURANCE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (121, 45,1, 'SANLAM ASSURANCE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(122, 70,1, 'SANLAM ASSURANCE GUINEE', '', '', '', '', NULL, NULL, NULL),
(123, 109,1, 'SANLAM ASSURANCE MALI', '', '', '', '', NULL, NULL, NULL),
(124, 21,1, 'SANLAM ASSURANCE VIE BENIN', '', '', '', '', NULL, NULL, NULL),
(125, 31,1, 'SANLAM ASSURANCE VIE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
(126, 45,1, 'SANLAM ASSURANCE VIE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (127, 109,1, 'SANLAM ASSURANCE VIE MALI', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (128, 34,1, 'SAMARITAN INSURANCE INC. CAMEROUN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (129, 34,1, 'SAMIRIS S.A. CAMEROUN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (130, 9,1, 'SAUDI RE ARABIE SAOUDITE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (131, 63,1, 'SCG-RE GABON', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (132, 62,1, 'SCOR SE FRANCE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (133, 45,1, 'SCR COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(134, 22,1, 'SCR MAROC', '', '', '', '', NULL, NULL, NULL),
(135, 162,1, 'SEN-RE SENEGAL', '', '', '', '', NULL, NULL, NULL),
(136, 45,1, 'SERENITY SA COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (137, 45,1, 'SMABTP COTE D\'IVOIRE S.A', '', '', '', '', NULL, NULL, NULL),
(138, 45,1, 'SOCIETE AFRICAINE D\'ASSURANCES ET DE REASSURANCES DE COTE D\'IVOIRE (SAAR-CI)', '', '', '', '', NULL, NULL, NULL),
(139, 45,1, 'SOCIETE AFRICAINE D\'ASSURANCES ET DE REASSURANCES VIE COTE D\'IVOIRE (SAAR-VIE CI)', '', '', '', '', NULL, NULL, NULL),
(140, 45,1, 'SOCIETE DU MILLENAIRE D\'ASSURANCE VIE COTE D\'IVOIRE (SOMAVIE)', '', '', '', '', NULL, NULL, NULL),
(141, 146,1, 'SOCIÉTÉ FINANCIÈRE D’ASSURANCE RDC', '', '', '', '', NULL, NULL, NULL),
(142, 45,1, 'SOCIETE INTERNATIONALE D\'ASSURANCES MULTIRISQUES COTE D\'IVOIRE (SIDAM S.A)', '', '', '', '', NULL, NULL, NULL),
(143, 45,1, 'SOCIETE INTERNATIONALE D\'ASSURANCES MUTUELLES COTE D\'IVOIRE(SIDAM)', '', '', '', '', NULL, NULL, NULL),
(144, 70,1, 'SOGAM SA GUINEE', '', '', '', '', NULL, NULL, NULL),
(145, 162,1, 'SONAC SENEGAL', '', '', '', '', NULL, NULL, NULL),
(146, 70,1, 'SONAG GUINEE', '', '', '', '', NULL, NULL, NULL),
(147, 45,1, 'SONAM ASSURANCES COTE D\'IVOIRE (EX 3A IARD)', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (148, 45,1, 'SONAM VIE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(149, 31,1, 'SONAR IARD BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
(150, 31,1, 'SONAR VIE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
(151, 146,1, 'SONAS RDC', '', '', '', '', NULL, NULL, NULL),
(152, 109,1, 'SONAVIE MALI', '', '', '', '', NULL, NULL, NULL),
(153, 45,1, 'STANE ASSURANCES COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (154, 109,1, 'SUMU ASSURANCES MALI', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (155, 21,1, 'SUNU ASSURANCES BENIN', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (156, 70,1, 'SUNU ASSURANCES GUINEE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (157, 45,1, 'SUNU ASSURANCES IARD COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(158, 146,1, 'SUNU ASSURANCES RDC', '', '', '', '', NULL, NULL, NULL),
(159, 21,1, 'SUNU ASSURANCES VIE BENIN', '', '', '', '', NULL, NULL, NULL),
(160, 45,1, 'SUNU ASSURANCES VIE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (161, 31,1, 'SUNU IARD BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (162, 31,1, 'SUNU VIE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (163, 45,1, 'SWISS RE AFRICA', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (164, 185,1, 'TUNIS-RE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (165, 31,1, 'UAB IARD BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (166, 31,1, 'UAB VIE BURKINA FASO', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (167, 70,1, 'UGAR ACTIVA GUINEE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (168, 100,1, 'UMBRELLA REINSURANCE COMPANY LIBYE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (169, 70,1, 'VISTA ASSURANCES GUINÉE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (170, 45,1, 'WAFA ASSURANCE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(171, 45,1, 'WAFA ASSURANCE COTE D\'IVOIRE VIE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (172, 185,1, 'WAICA RE TUNISIE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (173, 45,1, 'WAICA-RE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
(174, 66,1, 'WAICA-RE GHANA', '', '', '', '', NULL, NULL, NULL),
(175, 165,1, 'WAICA-RE SIERRA LEONE', '', '', '', '', NULL, NULL, NULL),
(176, 66,1, 'W-SAFE REINSURANCE LTD GHANA', '', '', '', '', NULL, NULL, NULL),
(177, 34,1, 'ZENITHE INSURANCE CAMEROUN', '', '', '', '', NULL, NULL, NULL),
(178, 45,1, 'ZEP-RE COTE D\'IVOIRE', '', '', '', '', NULL, NULL, NULL),
                                                                                                                                                                 (179, 146,1, 'ZEP-RE REPUBLIQUE DEMOCRATIQUE DU CONGO', '', '', '', '', NULL, NULL, NULL);